[project]
name = "photo-export"
version = "0.0.0"
description = "Tool to export photos from the child diary app."
authors = [{ name = "Samuel Pedro" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "tenacity>=9.1.2",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pytest-dotenv",
    "types-requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false
